### ISSUE TITLE
[SF 3105] Error on login

### ISSUE THREAD

**Issue by Rasgnarok** [Mineaurion/AurionVoteListener#20]
`[20:26:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[20:26:26] [Server thread/INFO] [net.minecraft.server.management.PlayerList]: CrimsonSupernova[/73.67.162.27:56981] logged in with entity id 82082 in vanha(0) at (-3611.0749679154096, 68.0, -3700.9973173487765)
[20:26:26] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=aurionsvotelistener, name=AurionsVoteListener, version=1.9, description=A votifier listener for Sponge, authors=[THEJean_Kevin], source=/home/miasku/minecraft/oblique/prod/terra/mods/AurionVoteListener.2.0.API.7_1.jar}
java.lang.NullPointerException: null
        at com.mineaurion.aurionVoteListener.EventManager.onPlayerJoin(EventManager.java:70) ~[EventManager.class:?]
        at org.spongepowered.common.event.listener.JoinListener_EventManager_onPlayerJoin98.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3105]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3105]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3105]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:404) `

Using SF 3105 and latest Aurions

**Comment by THEJean-Kevin** [comment]
fix with version 2.2
