### ISSUE TITLE
NPE on cumulative rewards

### ISSUE THREAD

**Issue by Rasgnarok** [Mineaurion/AurionVoteListener#21]
`[20:53:56] [Server thread/ERROR] [Sponge]: Could not pass VotifierEvent to Plugin{id=aurionsvotelistener, name=AurionsVoteListener, version=1.9, description=A votifier listener for Sponge, authors=[THEJean_Kevin], source=./mods/AurionVoteListener.2.0.API.7_1.jar}
java.lang.NullPointerException: null
	at com.mineaurion.aurionVoteListener.Rewards.cumulative(Rewards.java:265) ~[Rewards.class:?]
	at com.mineaurion.aurionVoteListener.Rewards.online(Rewards.java:76) ~[Rewards.class:?]
	at com.mineaurion.aurionVoteListener.EventManager.onVote(EventManager.java:35) ~[EventManager.class:?]
	at org.spongepowered.common.event.listener.VotifierEventListener_EventManager_onVote111.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:381) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:419) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:403) ~[SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:442) ~[SpongeEventManager.class:1.12.2-2705-7.1.0-BETA-3151]
	at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:348) ~[VotifierPlugin$3.class:?]
	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3151]
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_171]
	at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2705-7.1.0-BETA-3151]
	at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:323) [SpongeMod.class:1.12.2-2705-7.1.0-BETA-3151]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_25_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) [EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:590) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`

**Comment by THEJean-Kevin** [comment]
Can you send me your cumulative reward setting please

**Comment by Rasgnarok** [comment]
[config.zip](https://github.com/Mineaurion/AurionVoteListener/files/2107503/config.zip)

**Comment by THEJean-Kevin** [comment]
Sorry for the wait, many problems appeared suddenly and I had trouble with all the answers.
Tell me if the new version correct your problem

**Comment by Yann151924** [comment]
No answer
