### ISSUE TITLE
weird error in console

### ISSUE THREAD

**Issue by ThePro1604** [Mineaurion/AurionVoteListener#32]
im getting this weird error in console and i dont know what it means

[12:41:37] [HikariPool-1 housekeeper/WARN] [com.zaxxer.hikari.pool.ProxyLeakTask]: Connection leak detection triggered for org.sqlite.SQLiteConnection@3c91e6f4, stack trace followsjava.lang.Exception: Apparent connection leak detectedat com.mineaurion.aurionvotelistener.Main.initialiseDatabase(Main.java:135) ~[Main.class:?]at com.mineaurion.aurionvotelistener.Main.onServerReload(Main.java:100) ~[Main.class:?]at org.spongepowered.common.event.listener.GameReloadEventListener_Main_onServerReload7.handle(Unknown Source) ~[?:?]at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) ~[SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) ~[SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) ~[SpongeModEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) ~[SpongeEventManager.class:1.12.2-2768-7.1.4]at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:242) ~[SpongeImpl.class:1.12.2-2768-7.1.4]at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$8(SpongeCommandFactory.java:600) ~[SpongeCommandFactory.class:1.12.2-2768-7.1.4]at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.4]at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.4]at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.4]at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) ~[SpongeCommandManager.class:1.12.2-2768-7.1.4]at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[dh.class:?]at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) ~[pa.class:?]at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) ~[pa.class:?]at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[la.class:?]at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[la.class:?]at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.4]at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) ~[SpongeImplHooks.class:1.12.2-2768-7.1.4]at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) ~[MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) ~[MinecraftServer.class:?]at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by X-Niter** [comment]
I as well am getting the same thing. Will post it under this message to see if they show anything helpful.





-------------------------------------------------------------------------------------------------------------------
10.06 13:02:51 [Server] HikariPool-3 housekeeper/WARN [com.zaxxer.hikari.pool.ProxyLeakTask]: Connection leak detection triggered for org.sqlite.SQLiteConnection@155b19e3, stack trace follows
10.06 13:02:51 [Server] INFO java.lang.Exception: Apparent connection leak detected
10.06 13:02:51 [Server] INFO at com.mineaurion.aurionvotelistener.Main.initialiseDatabase(Main.java:135) ~[Main.class:?]
10.06 13:02:51 [Server] INFO at com.mineaurion.aurionvotelistener.Main.onServerReload(Main.java:100) ~[Main.class:?]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.event.listener.GameReloadEventListener_Main_onServerReload98.handle(Unknown Source) ~[?:?]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:385) ~[SpongeModEventManager.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:458) ~[SpongeModEventManager.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:419) ~[SpongeModEventManager.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) ~[SpongeEventManager.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:246) ~[SpongeImpl.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.command.SpongeCommandFactory.lambda$createSpongePluginsCommand$8(SpongeCommandFactory.java:614) ~[SpongeCommandFactory.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) ~[SpongeCommandManager.class:1.12.2-2825-7.1.6]
10.06 13:02:51 [Server] INFO at net.minecraft.command.ServerCommandManager.executeCommand(SourceFile:1156) ~[dh.class:?]
10.06 13:02:51 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.executePendingCommands(DedicatedServer.java:433) ~[nz.class:?]
10.06 13:02:51 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:398) ~[nz.class:?]
10.06 13:02:51 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
10.06 13:02:51 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) ~[MinecraftServer.class:?]
10.06 13:02:51 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by Yann151924** [comment]
Dupplicate of #28
