### ISSUE TITLE
An issue

### ISSUE THREAD

**Issue by aWitch-Doctor** [Mineaurion/AurionVoteListener#4]
I am running the latest version of sponge vanilla api 5 and i just updated your plugin to the latest to make sure that wasn't the issue. I have the config set to give @a players 1 bedrock and give <username> 1 cake. This works for the most part.

I have onlineonly set to false, if i vote while offline I should receive a bedrock and a cake on login right? I have setup a mysql db. When I login I dont get either item though.
 
If the player is holding something in their hand when your plugin trys to give them an item, the console is spammed with the error below. If they arent holding anything in their hand it works fine.

[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: java.lang.Exception: Stack trace
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.lang.Thread.dumpStack(Thread.java:1329)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.entity.EntityTracker.handler$onAddEntityToTracker$zcn000(SourceFile:575)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.entity.EntityTracker.func_72785_a(SourceFile)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.entity.EntityTracker.func_72786_a(SourceFile:105)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.ServerWorldEventHandler.func_72703_a(SourceFile:37)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.World.func_72923_a(SourceFile:898)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.WorldServer.func_72923_a(SourceFile:974)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.WorldServer.onSpongeEntityAdded(SourceFile:2696)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.WorldServer.forceSpawnEntity(SourceFile:2743)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.WorldServer.forceSpawnEntity(SourceFile:2726)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.phase.general.GeneralState.spawnEntityOrCapture(GeneralState.java:82)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.phase.general.GeneralPhase.spawnEntityOrCapture(GeneralPhase.java:355)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.tracking.CauseTracker.spawnEntity(CauseTracker.java:623)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.world.WorldServer.func_72838_d(SourceFile:2467)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.entity.EntityUtil.dropItemAndGetStack(EntityUtil.java:1134)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.entity.EntityUtil.playerDropItem(EntityUtil.java:1094)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.entity.player.EntityPlayer.func_146097_a(SourceFile:3024)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.entity.player.EntityPlayer.func_71019_a(SourceFile:2965)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.command.CommandGive.func_184881_a(SourceFile:75)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at net.minecraft.command.CommandHandler.func_175786_a(SourceFile:82)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:151)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:129)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at com.mineaurion.tjk.AurionsVoteListener.RewardsTask.online(RewardsTask.java:56)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at com.mineaurion.tjk.AurionsVoteListener.AurionsVoteListener.onVote(AurionsVoteListener.java:432)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.listener.VotifierEventListener_AurionsVoteListener_onVote9.handle(Unknown Source)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:356)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:183)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[02:54:32] [pool-2-thread-85/ERROR] [STDERR]: 	at java.lang.Thread.run(Thread.java:745)
[02:54:32] [pool-2-thread-85/ERROR] [Sponge]: Detected attempt to add entity 'EntityItem['item.tile.bedrock'/3787, l='Kappa', x=-804.63, y=55.32, z=1480.22]' to tracker asynchronously.
 This is very bad as it can cause ConcurrentModificationException's during a server tick.
 Skipping...

**Comment by THEJean-Kevin** [comment]
I check the problem this week-end or this afternoon if i have the time

**Comment by THEJean-Kevin** [comment]
So first, if you put onlineonly to false, Minecraft Will not be able to give item on offline player so i add your username on waiting list.

And for the error i need to check more the problem and try to correct but i think it's not my plugin but rather minecraft

**Comment by THEJean-Kevin** [comment]
Just you have this error when you are connected on your server or not?

**Comment by THEJean-Kevin** [comment]
If you are not connected, its normal to have this error, because you have set onlineOnly to false and minecraft will not able to give item when the player is offline. I Change this for remove this problem.

So can you set onlineOnly to true, and try to vote when you have an item in your hand

Thx you

**Comment by aWitch-Doctor** [comment]
Ill give that a try in the morning. All players have the same issue, if they vote offline then login they don't get the item. The error shows up for everyone that is online and has an item in their hand.

**Comment by THEJean-Kevin** [comment]
@aWitch-Doctor Just can you give me rewards config, because i try to reproduce the error, but it's work for me. And when i check the error you try to give an entity

**Comment by aWitch-Doctor** [comment]
Mkay, sorry it took me so long to get back to you. Life happened and this is the first chance i've had. So I made sure the config is updated to the latest version, and I set offlineonly to true. The error is still coming up. Here is the config I am using minus the sql info. The error happens for all players that are online and holding an item or have a full inventory at the time of vote and also when I am offline and vote it gives the error for the first reason and an error for my name for the cake.

[aurionsvotelistener.txt](https://github.com/Mineaurion/AurionVoteListener/files/950365/aurionsvotelistener.txt)

**Comment by THEJean-Kevin** [comment]
I don't understand your error, It's work perfectly for me, when I have full inventory, the items are dropped on the ground.

So Either you have a problem with your minecraft version, Either you have config an other plugin who block give.

If you have discord, come on this dicord and contact me https://discordapp.com/invite/px5Mq8y

![image](https://cloud.githubusercontent.com/assets/19693105/25345713/acc15dd0-28e3-11e7-8d3b-d36b69aee328.png)

**Comment by THEJean-Kevin** [comment]
Configuration problem. Correct with the person
